name: GriefLog
version: 4.9.8beta4
main: tk.blackwolf12333.grieflog.GriefLog
softdepend: [WorldEdit]
commands:
    glog:
        description: Main command, type /glog help for more info.
        usage: /glog <option> <arguments>
permissions:
    grieflog.*:
        description: Gives access to all GriefLog commands
        default: op
        children:
            grieflog.search: true
            grieflog.rollback: true
            grieflog.tool: true
            grieflog.reload: true
            grieflog.page: true
            grieflog.getwarning: true
            grieflog.tpto: true
    grieflog.getwarning.*:
        description: Permission to get a warning when someone does something that indicates that he has a modified client.
        default: false
        children:
            grieflog.getwarning.breakair: true
        
